global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Smart Document Bot Backend
  - job_name: 'smart-doc-bot-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Smart Document Bot Frontend
  - job_name: 'smart-doc-bot-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # ChromaDB Vector Database
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Open Policy Agent
  - job_name: 'opa'
    static_configs:
      - targets: ['opa:8181']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # cAdvisor Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Filebeat
  - job_name: 'filebeat'
    static_configs:
      - targets: ['filebeat:5066']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Docker Daemon
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s

  # Custom Application Metrics
  - job_name: 'smart-doc-bot-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    honor_labels: true
    metrics_path: '/api/v1/metrics/prometheus'

  # Agent Performance Metrics
  - job_name: 'agent-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/agents/metrics'
    scrape_interval: 15s

  # Workflow Metrics
  - job_name: 'workflow-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/workflows/metrics'
    scrape_interval: 15s

  # System Health Checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:8000'
        - 'frontend:3000'
        - 'postgres:5432'
        - 'redis:6379'
        - 'chromadb:8000'
        - 'elasticsearch:9200'
        - 'grafana:3000'
        - 'prometheus:9090'
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 10s
